#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libunwind
Version  : 1.3.1
Release  : 23
URL      : http://download.savannah.gnu.org/releases/libunwind/libunwind-1.3.1.tar.gz
Source0  : http://download.savannah.gnu.org/releases/libunwind/libunwind-1.3.1.tar.gz
Summary  : Portable and efficient C programming interface (API) to determine the call-chain of a program
Group    : Development/Tools
License  : MIT
Requires: libunwind-lib = %{version}-%{release}
Requires: libunwind-license = %{version}-%{release}
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libatomic_ops-dev
BuildRequires : xz-dev

%description
[![Build Status](https://travis-ci.org/libunwind/libunwind.svg?branch=master)](https://travis-ci.org/libunwind/libunwind)

%package dev
Summary: dev components for the libunwind package.
Group: Development
Requires: libunwind-lib = %{version}-%{release}
Provides: libunwind-devel = %{version}-%{release}

%description dev
dev components for the libunwind package.


%package dev32
Summary: dev32 components for the libunwind package.
Group: Default
Requires: libunwind-lib32 = %{version}-%{release}
Requires: libunwind-dev = %{version}-%{release}

%description dev32
dev32 components for the libunwind package.


%package lib
Summary: lib components for the libunwind package.
Group: Libraries
Requires: libunwind-license = %{version}-%{release}

%description lib
lib components for the libunwind package.


%package lib32
Summary: lib32 components for the libunwind package.
Group: Default
Requires: libunwind-license = %{version}-%{release}

%description lib32
lib32 components for the libunwind package.


%package license
Summary: license components for the libunwind package.
Group: Default

%description license
license components for the libunwind package.


%prep
%setup -q -n libunwind-1.3.1
pushd ..
cp -a libunwind-1.3.1 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1547058431
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="$ASFLAGS --32"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%install
export SOURCE_DATE_EPOCH=1547058431
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libunwind
cp COPYING %{buildroot}/usr/share/package-licenses/libunwind/COPYING
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libunwind-coredump.so
/usr/lib64/libunwind-generic.so
/usr/lib64/libunwind-ptrace.so
/usr/lib64/libunwind-setjmp.so
/usr/lib64/libunwind-x86_64.so
/usr/lib64/libunwind.so
/usr/lib64/pkgconfig/libunwind-coredump.pc
/usr/lib64/pkgconfig/libunwind-generic.pc
/usr/lib64/pkgconfig/libunwind-ptrace.pc
/usr/lib64/pkgconfig/libunwind-setjmp.pc
/usr/lib64/pkgconfig/libunwind.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libunwind-coredump.so
/usr/lib32/libunwind-generic.so
/usr/lib32/libunwind-ptrace.so
/usr/lib32/libunwind-setjmp.so
/usr/lib32/libunwind-x86.so
/usr/lib32/libunwind.so
/usr/lib32/pkgconfig/32libunwind-coredump.pc
/usr/lib32/pkgconfig/32libunwind-generic.pc
/usr/lib32/pkgconfig/32libunwind-ptrace.pc
/usr/lib32/pkgconfig/32libunwind-setjmp.pc
/usr/lib32/pkgconfig/32libunwind.pc
/usr/lib32/pkgconfig/libunwind-coredump.pc
/usr/lib32/pkgconfig/libunwind-generic.pc
/usr/lib32/pkgconfig/libunwind-ptrace.pc
/usr/lib32/pkgconfig/libunwind-setjmp.pc
/usr/lib32/pkgconfig/libunwind.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libunwind-coredump.so.0
/usr/lib64/libunwind-coredump.so.0.0.0
/usr/lib64/libunwind-ptrace.so.0
/usr/lib64/libunwind-ptrace.so.0.0.0
/usr/lib64/libunwind-setjmp.so.0
/usr/lib64/libunwind-setjmp.so.0.0.0
/usr/lib64/libunwind-x86_64.so.8
/usr/lib64/libunwind-x86_64.so.8.0.1
/usr/lib64/libunwind.so.8
/usr/lib64/libunwind.so.8.0.1

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libunwind-coredump.so.0
/usr/lib32/libunwind-coredump.so.0.0.0
/usr/lib32/libunwind-ptrace.so.0
/usr/lib32/libunwind-ptrace.so.0.0.0
/usr/lib32/libunwind-setjmp.so.0
/usr/lib32/libunwind-setjmp.so.0.0.0
/usr/lib32/libunwind-x86.so.8
/usr/lib32/libunwind-x86.so.8.0.1
/usr/lib32/libunwind.so.8
/usr/lib32/libunwind.so.8.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libunwind/COPYING
