#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libunwind
Version  : 1.1
Release  : 11
URL      : http://download.savannah.gnu.org/releases/libunwind/libunwind-1.1.tar.gz
Source0  : http://download.savannah.gnu.org/releases/libunwind/libunwind-1.1.tar.gz
Summary  : libunwind generic library
Group    : Development/Tools
License  : MIT
Requires: libunwind-lib
Requires: libunwind-doc
Patch1: cve-2015-3239.patch

%description
This is version 1.0 of the unwind library.  This library supports
several architecture/operating-system combinations:

%package dev
Summary: dev components for the libunwind package.
Group: Development
Requires: libunwind-lib

%description dev
dev components for the libunwind package.


%package doc
Summary: doc components for the libunwind package.
Group: Documentation

%description doc
doc components for the libunwind package.


%package lib
Summary: lib components for the libunwind package.
Group: Libraries

%description lib
lib components for the libunwind package.


%prep
%setup -q -n libunwind-1.1
%patch1 -p1

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make check || :

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
